---
- name: Using our new module
  hosts: localhost

  tasks:
  - name: New module
    my_custom_test_module:
      name: potatosalad 
      ingredient: bacon
      augment: true
    register: results

  - debug:
      var: results

